const usersDataOut = [
  {
    id: 0,
    resi: "0298273",
    sender: "Erald",
    receiver: "Algi",
    phone: "0822",
    from: "medan",
    to: "perawang",
    status: "Pending",
  },
  {
    id: 1,
    resi: "0298274",
    sender: "Eraldsss",
    receiver: "Algi",
    phone: "0822",
    from: "medan",
    to: "perawang",
    status: "Pending",
  },
  {
    id: 0,
    resi: "0298273",
    sender: "Erald",
    receiver: "Algi",
    phone: "0822",
    from: "medan",
    to: "perawang",
    status: "Pending",
  },
  {
    id: 0,
    resi: "0298273",
    sender: "Erald",
    receiver: "Algi",
    phone: "0822",
    from: "medan",
    to: "perawang",
    status: "Pending",
  },
  {
    id: 0,
    resi: "0298273",
    sender: "Erald",
    receiver: "Algi",
    phone: "0822",
    from: "medan",
    to: "perawang",
    status: "Pending",
  },
  {
    id: 0,
    resi: "0298273",
    sender: "Erald",
    receiver: "Algi",
    phone: "0822",
    from: "medan",
    to: "perawang",
    status: "Pending",
  },
  {
    id: 0,
    resi: "0298273",
    sender: "Erald",
    receiver: "Algi",
    phone: "0822",
    from: "medan",
    to: "perawang",
    status: "Pending",
  },
  {
    id: 0,
    resi: "0298273",
    sender: "Erald",
    receiver: "Algi",
    phone: "0822",
    from: "medan",
    to: "perawang",
    status: "Pending",
  },
  {
    id: 0,
    resi: "0298273",
    sender: "Erald",
    receiver: "Algi",
    phone: "0822",
    from: "medan",
    to: "perawang",
    status: "Pending",
  },
  {
    id: 0,
    resi: "0298273",
    sender: "Erald",
    receiver: "Algi",
    phone: "0822",
    from: "medan",
    to: "perawang",
    status: "Pending",
  },
];

export default usersDataOut;
